name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: snyk/actions/setup@master
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: "Snyk library issue test"
        run: snyk test --all-projects --reachable || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: "Snyk library issues to snyk.io"
        run: snyk monitor --all-projects --reachable || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: "Snyk code scan test"
        run: snyk code test || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
